version: '3'
services:
  flask:
    build:
      context: SimuApp
      dockerfile: Dockerfile
    container_name: flask
    restart: unless-stopped
    environment:
      APP_ENV: "dev"
      APP_DEBUG: "True"
      APP_PORT: 5000
      SIMU_MODE: "dev"
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: mongodbuser
      MONGODB_PASSWORD: your_mongodb_root_password
      MONGODB_HOSTNAME: mongodb
      MONGODB_PORT: 27017
    ports:
      - "5000:5000"
    volumes:
      - ./SimuApp:/var/www
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: your_mongodb_root_password
      MONGO_INITDB_DATABASE: flaskdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    ports:
      - "27018:27017"
    networks:
      - backend

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "false"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - flask
    networks:
      - frontend

  scrubber:
    build:
      context: scrubber
      dockerfile: Dockerfile
    container_name: scrubber
    restart: unless-stopped
    environment:
      MONGODB_DATABASE: flaskdb
      MONGODB_USERNAME: mongodbuser
      MONGODB_PASSWORD: your_mongodb_root_password
      MONGODB_HOSTNAME: mongodb
      MONGODB_PORT: 27017
    volumes:
      - ./scrubber:/app
    depends_on:
      - mongodb
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
  nginxdata:
    driver: local